// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjVNupq5sES1Lim-R9CBrGs4vwFxWRCuQ',
    appId: '1:671693178561:web:6c294e87f97f57facd7640',
    messagingSenderId: '671693178561',
    projectId: 'tamuhack-2023',
    authDomain: 'tamuhack-2023.firebaseapp.com',
    storageBucket: 'tamuhack-2023.appspot.com',
    measurementId: 'G-QDEMPP0428',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtu_FdeH2LXwDQraPBMukIqNBW3NXpjDc',
    appId: '1:671693178561:android:b3ee74727a7fb477cd7640',
    messagingSenderId: '671693178561',
    projectId: 'tamuhack-2023',
    storageBucket: 'tamuhack-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFE0cCayocdxAeYfR_ZYu0i0ujTjBHa0',
    appId: '1:671693178561:ios:17a5c9a8dbe2296ccd7640',
    messagingSenderId: '671693178561',
    projectId: 'tamuhack-2023',
    storageBucket: 'tamuhack-2023.appspot.com',
    iosClientId: '671693178561-97di7ttpqd03qa8t00parbvnta290ts1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamuhack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhFE0cCayocdxAeYfR_ZYu0i0ujTjBHa0',
    appId: '1:671693178561:ios:17a5c9a8dbe2296ccd7640',
    messagingSenderId: '671693178561',
    projectId: 'tamuhack-2023',
    storageBucket: 'tamuhack-2023.appspot.com',
    iosClientId: '671693178561-97di7ttpqd03qa8t00parbvnta290ts1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamuhack',
  );
}
